import { NextResponse } from 'next/server';

import fs from 'fs';
import path from 'path';

export async function POST(request: Request) {
    try {
        const apiKey = process.env.GOOGLE_API_KEY;
        if (!apiKey) {
            return NextResponse.json({ error: 'GOOGLE_API_KEY is not configured' }, { status: 500 });
        }

        const { title, category, summary, transcript } = await request.json();

        if (!title) {
            return NextResponse.json({ error: 'Title is required' }, { status: 400 });
        }

        // Construct a rich prompt based on available data
        let context = `Title: ${title}\nCategory: ${category || 'General'}`;
        if (summary) context += `\nSummary: ${summary.slice(0, 300)}...`; // Limit summary length
        if (transcript) context += `\nTranscript Snippet: ${transcript.slice(0, 300)}...`; // Limit transcript length

        const prompt = `Create a minimalist, high-quality vector art style illustration for a lecture cover.
The design should be clean, modern, and flat, featuring a cute banana character (Nanobanana) dressed as a doctor or medical professional.
The character should be interacting with elements related to the following medical topic:
${context}

Key visual requirements:
- Style: Minimalist, Flat Design, Vector Art
- Background: Solid color or simple soft gradient (pastel tones preferred)
- Character: Cute Nanobanana doctor (yellow banana with doctor's coat/stethoscope)
- Composition: Centered, balanced, plenty of negative space
- NO TEXT in the image.
- Mood: Professional yet approachable and friendly.`;

        console.log('Generating image with Google Gemini 3 Pro, prompt length:', prompt.length);

        // Call Google Gemini 3 Pro Image API via REST
        // Using gemini-3-pro-image-preview as the model
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-image-preview:predict?key=${apiKey}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                instances: [
                    {
                        prompt: prompt,
                    }
                ],
                parameters: {
                    sampleCount: 1,
                    aspectRatio: "16:9", // Better for lecture covers
                    includeRaiReasoning: false
                }
            })
        });

        if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            console.error('Google API Error:', response.status, JSON.stringify(errorData));
            throw new Error(`Google API Error: ${response.status} - ${errorData.error?.message || response.statusText}`);
        }

        const data = await response.json();
        const imageBase64 = data.predictions?.[0]?.bytesBase64Encoded;

        if (!imageBase64) {
            throw new Error("No image generated by Google API");
        }

        // Ensure public/covers exists
        const coversDir = path.join(process.cwd(), 'public', 'covers');
        if (!fs.existsSync(coversDir)) {
            fs.mkdirSync(coversDir, { recursive: true });
        }

        const filename = `cover-${Date.now()}.png`;
        const filepath = path.join(coversDir, filename);

        // Save file
        const buffer = Buffer.from(imageBase64, 'base64');
        fs.writeFileSync(filepath, buffer);

        const imageUrl = `/covers/${filename}`;

        return NextResponse.json({ url: imageUrl });

    } catch (error: any) {
        console.error('Error generating image:', error);
        return NextResponse.json({ error: error.message || 'Failed to generate image' }, { status: 500 });
    }
}
